### ISSUE TITLE
PMSD001

### ISSUE THREAD

**Issue by PanderMusubi** [blademoon/Sensus#5]
Could you support the PMSD001 sensor?

https://www.pine64.org/?product=pine64-humidity-temperature-sensor

**Comment by blademoon** [comment]
Hi! I have this sensor. And i can write code for this sensor on the weekend. You can get original code for use herein: https://github.com/ControlEverythingCommunity/SI7021/blob/master/C/SI7021.c
Base on Silicon Labs Si7021 I2C Humidity and Temperature Sensor.

When I write a function to this sensor, I will write to you. Good?

**Comment by PanderMusubi** [comment]
Ah, see also https://github.com/gregarmer/pine64-temp-humidity

**Comment by PanderMusubi** [comment]
PS The documentation is not exactly refering to the proper file names.

**Comment by blademoon** [comment]
Hello Pander. I've already written the code for si7021 sensor. More remains to rewrite the code for bme280 sensor and write some code for the sensor:
https://ru.aliexpress.com/item/DIYmall-TCS34725-RGB-Color-Sensor-with-IR-Filter-and-White-LED-for-Arduino-UNO-R3/32715720307.html?spm=2114.13010608. 0.0.LGVypY

**Comment by blademoon** [comment]
HI Pander. I have few question for you:
1. Where are you from? I'm from Siberia, Russia.
2. I transcribe sensors library in connection with this, I wonder. Would it be better if one call to the function will be immediately Returns an all parameters measured by the sensor? Or is it better to leave as is, one call to the function introduction will take you back one parameter measured by the sensor?
3. Do the conversion value in fuktsii necessary. For example, we measure the temperature. The function Returns an opportunity to receive the temperature in degrees Celsius or Fahrenheit, or Kelvin. This functionality is needed?

**Comment by PanderMusubi** [comment]
Sorry for not responding earlier. I'm not from Russia by the way. If all data is stored near each other and it is not that much data, just return all in one call. But if same soft of software is used for calls to other sensors that e.g. only have temperature, then also offer the individual calls. For Celcius, Fahrenheit or Kelvin, the most common is to offer Celcius. If it needs to be as quick as possible, offer in the format in which the sensor gives is. End-users can translate it themselves.

**Comment by PanderMusubi** [comment]
No a PINE64 with a PMSD001 sensor on I²C.

**Comment by blademoon** [comment]
I rewrote almost the entire library so that it becomes more convenient, more stable and better. A few screenshots ...
https://yadi.sk/i/T5j3N8MJ3FHYRn

**Comment by blademoon** [comment]
Hi again. I started creating a new repository. I posted a library of sensors for Pine64. Can you test on your sensor?
https://github.com/blademoon/sensus-library
