### ISSUE TITLE
Upstream support

### ISSUE THREAD

**Issue by PanderMusubi** [blademoon/Sensus#6]
Will support for the developed software for sensors here be offered/asked upstream for linux kernel https://hwmon.wiki.kernel.org/ or lm-sensors https://github.com/groeck/lm-sensors ?

**Comment by blademoon** [comment]
Hi again. Sorry, but i didn't undestand what you mean... English is not my not my natural language...

**Comment by blademoon** [comment]
Can you more fully explain what you wanted to say? I do not quite understand ... When translating into the Russian language, the meaning becomes blurred ...

**Comment by PanderMusubi** [comment]
If possible, send your work upstream to kernel or lm-sensors. Then there will be more people maintaining it and more people using it.

**Comment by blademoon** [comment]
Honestly, I'm writing this library for myself, and those to whom it can come in handy. I did not set myself such an ambitious task - to write the kernel linux.

**Comment by PanderMusubi** [comment]
No problem, was only a suggestion.

**Comment by blademoon** [comment]
First I will publish a version of the library 2.0. Then we'll see.
